"""trustrail — Production-grade Python library for GenAI/LLM guardrails.

Quick start:

    from trustrail import Guard, GuardStage

    guard = Guard.balanced()
    result = guard.check("Hello, world!", GuardStage.USER_INPUT)
    print(result.action)  # GuardAction.ALLOW
"""

from importlib.metadata import PackageNotFoundError, version

from trustrail.agency import StaticToolApprovalVerifier, ToolAuthorizer, ToolExecutionBudget
from trustrail.audit import LoggingAuditSink, MemoryAuditSink, NullAuditSink
from trustrail.exceptions import (
    AegisRailError,
    ApprovalRequiredError,
    ArtifactVerificationError,
    ConfigurationError,
    DataPoisoningError,
    GroundingVerificationError,
    GuardrailBlockedError,
    OutputHandlingError,
    ProviderError,
    RateLimitError,
    ResourceBudgetError,
    ResourceLimitError,
    SystemPromptLeakageError,
    SystemPromptValidationError,
    ToolAuthorizationError,
    VectorVerificationError,
)
from trustrail.grounding import EvidenceGroundingVerifier
from trustrail.guard import Guard
from trustrail.models.agency import (
    AuthorizedToolCall,
    ToolApprovalGrant,
    ToolArgumentConstraint,
    ToolArgumentKind,
    ToolAuthorizationCode,
    ToolAuthorizationFinding,
    ToolAuthorizationPolicy,
    ToolAuthorizationRequest,
    ToolAuthorizationResult,
    ToolCapability,
    ToolEffect,
    ToolIntent,
    ToolPrincipal,
    ToolResource,
)
from trustrail.models.config import GuardConfig, GuardPolicy, RuleConfig
from trustrail.models.core import (
    AuditEvent,
    Document,
    GuardContext,
    GuardDecision,
    GuardFinding,
    GuardResult,
    Message,
    RiskScore,
    ToolCall,
    ToolResult,
)
from trustrail.models.enums import (
    FailMode,
    GuardAction,
    GuardStage,
    MemoryWriteClassification,
    OutputContext,
    RuleCategory,
    RulePhase,
    SensitiveDataMode,
    Severity,
    TrustLevel,
)
from trustrail.models.grounding import (
    ClaimKind,
    EvidenceRelation,
    EvidenceRelationKind,
    GroundingCitation,
    GroundingClaim,
    GroundingEvidence,
    GroundingFinding,
    GroundingPolicy,
    GroundingRequest,
    GroundingResult,
    GroundingSignal,
    GroundingSupportStatus,
    GroundingVerificationCode,
    HumanReviewDecision,
    HumanReviewGrant,
    ImpactDomain,
)
from trustrail.models.output_handling import (
    OutputHandlingCode,
    OutputHandlingFinding,
    OutputHandlingPolicy,
    OutputHandlingResult,
)
from trustrail.models.poisoning import (
    DataAssetKind,
    DataIngestionRecord,
    DataPoisoningPolicy,
    DataPoisoningResult,
    DataProvenance,
    DataSourcePolicy,
    DataTransformation,
    IngestionAuthorization,
    PoisoningCode,
    PoisoningFinding,
)
from trustrail.models.prompt import (
    PromptScanResult,
    PromptSegment,
    PromptSegmentResult,
    PromptSource,
)
from trustrail.models.rag import ProvenanceLabel, RAGContextEnvelope, RAGContextSegment
from trustrail.models.resource import (
    CompressedPayloadRequest,
    CompressionFormat,
    ConsumptionBudgetPolicy,
    DecompressionResult,
    ResourceBudgetResult,
    ResourceCompletionRequest,
    ResourceIdentity,
    ResourceLease,
    ResourceLimitCode,
    ResourceLimitFinding,
    ResourceOperationKind,
    ResourceReservationRequest,
    ResourceUsageSignal,
)
from trustrail.models.sensitive_data import ProtectedData
from trustrail.models.supply_chain import (
    ArtifactDigest,
    ArtifactKind,
    ArtifactManifest,
    ArtifactObservation,
    ArtifactRecord,
    ArtifactStatus,
    ArtifactVerificationCode,
    ArtifactVerificationFinding,
    ArtifactVerificationPolicy,
    ArtifactVerificationResult,
    DigestAlgorithm,
)
from trustrail.models.system_prompt import (
    SystemPromptDataClass,
    SystemPromptLeakageCode,
    SystemPromptLeakageFinding,
    SystemPromptLeakagePolicy,
    SystemPromptLeakageResult,
    SystemPromptPolicy,
    SystemPromptReference,
    SystemPromptTemplate,
    SystemPromptValidationCode,
    SystemPromptValidationFinding,
    SystemPromptValidationResult,
    SystemPromptVariable,
    ValidatedSystemPrompt,
)
from trustrail.models.vector import (
    AuthorizedVectorHit,
    VectorAccessPolicy,
    VectorChunk,
    VectorEmbedding,
    VectorIndexEntry,
    VectorPrincipal,
    VectorRetrievalHit,
    VectorRetrievalPolicy,
    VectorRetrievalRequest,
    VectorVerificationCode,
    VectorVerificationFinding,
    VectorVerificationResult,
)
from trustrail.output_handling import SafeOutputHandler, ValidatedToolCall
from trustrail.poisoning import DataPoisoningVerifier, PoisoningDetector
from trustrail.protocols import (
    ApprovalProvider,
    AsyncGuardRule,
    AuditSink,
    ContentSafetyProvider,
    GroundingVerifier,
    GuardRule,
    PromptInjectionProvider,
    SensitiveDataProvider,
    StateBackend,
    TokenCounter,
    ToolApprovalVerifier,
)
from trustrail.resource import BoundedDecompressor, ResourceBudgetManager
from trustrail.supply_chain import ArtifactVerifier
from trustrail.system_prompt import SystemPromptLeakageDetector, SystemPromptValidator
from trustrail.vector import SecureVectorWorkflow

try:
    __version__ = version("trustrail")
except PackageNotFoundError:
    __version__ = "0.0.0+unknown"
__all__ = [
    # Exceptions
    "AegisRailError",
    "ApprovalProvider",
    "ApprovalRequiredError",
    "ArtifactDigest",
    "ArtifactKind",
    "ArtifactManifest",
    "ArtifactObservation",
    "ArtifactRecord",
    "ArtifactStatus",
    "ArtifactVerificationCode",
    "ArtifactVerificationError",
    "ArtifactVerificationFinding",
    "ArtifactVerificationPolicy",
    "ArtifactVerificationResult",
    "ArtifactVerifier",
    "AsyncGuardRule",
    # Data models
    "AuditEvent",
    "AuditSink",
    "AuthorizedToolCall",
    "AuthorizedVectorHit",
    "BoundedDecompressor",
    "ClaimKind",
    "CompressedPayloadRequest",
    "CompressionFormat",
    "ConfigurationError",
    "ConsumptionBudgetPolicy",
    "ContentSafetyProvider",
    "DataAssetKind",
    "DataIngestionRecord",
    "DataPoisoningError",
    "DataPoisoningPolicy",
    "DataPoisoningResult",
    "DataPoisoningVerifier",
    "DataProvenance",
    "DataSourcePolicy",
    "DataTransformation",
    "DecompressionResult",
    "DigestAlgorithm",
    "Document",
    "EvidenceGroundingVerifier",
    "EvidenceRelation",
    "EvidenceRelationKind",
    "FailMode",
    "GroundingCitation",
    "GroundingClaim",
    "GroundingEvidence",
    "GroundingFinding",
    "GroundingPolicy",
    "GroundingRequest",
    "GroundingResult",
    "GroundingSignal",
    "GroundingSupportStatus",
    "GroundingVerificationCode",
    "GroundingVerificationError",
    "GroundingVerifier",
    # Core
    "Guard",
    "GuardAction",
    "GuardConfig",
    # Context / results
    "GuardContext",
    "GuardDecision",
    "GuardFinding",
    "GuardPolicy",
    "GuardResult",
    # Protocols
    "GuardRule",
    # Enums
    "GuardStage",
    "GuardrailBlockedError",
    "HumanReviewDecision",
    "HumanReviewGrant",
    "ImpactDomain",
    "IngestionAuthorization",
    # Audit sinks
    "LoggingAuditSink",
    "MemoryAuditSink",
    "MemoryWriteClassification",
    "Message",
    "NullAuditSink",
    "OutputContext",
    "OutputHandlingCode",
    "OutputHandlingError",
    "OutputHandlingFinding",
    "OutputHandlingPolicy",
    "OutputHandlingResult",
    "PoisoningCode",
    "PoisoningDetector",
    "PoisoningFinding",
    "PromptInjectionProvider",
    "PromptScanResult",
    "PromptSegment",
    "PromptSegmentResult",
    "PromptSource",
    "ProtectedData",
    "ProvenanceLabel",
    "ProviderError",
    "RAGContextEnvelope",
    "RAGContextSegment",
    "RateLimitError",
    "ResourceBudgetError",
    "ResourceBudgetManager",
    "ResourceBudgetResult",
    "ResourceCompletionRequest",
    "ResourceIdentity",
    "ResourceLease",
    "ResourceLimitCode",
    "ResourceLimitError",
    "ResourceLimitFinding",
    "ResourceOperationKind",
    "ResourceReservationRequest",
    "ResourceUsageSignal",
    "RiskScore",
    "RuleCategory",
    "RuleConfig",
    "RulePhase",
    "SafeOutputHandler",
    "SecureVectorWorkflow",
    "SensitiveDataMode",
    "SensitiveDataProvider",
    "Severity",
    "StateBackend",
    "StaticToolApprovalVerifier",
    "SystemPromptDataClass",
    "SystemPromptLeakageCode",
    "SystemPromptLeakageDetector",
    "SystemPromptLeakageError",
    "SystemPromptLeakageFinding",
    "SystemPromptLeakagePolicy",
    "SystemPromptLeakageResult",
    "SystemPromptPolicy",
    "SystemPromptReference",
    "SystemPromptTemplate",
    "SystemPromptValidationCode",
    "SystemPromptValidationError",
    "SystemPromptValidationFinding",
    "SystemPromptValidationResult",
    "SystemPromptValidator",
    "SystemPromptVariable",
    "TokenCounter",
    "ToolApprovalGrant",
    "ToolApprovalVerifier",
    "ToolArgumentConstraint",
    "ToolArgumentKind",
    "ToolAuthorizationCode",
    "ToolAuthorizationError",
    "ToolAuthorizationFinding",
    "ToolAuthorizationPolicy",
    "ToolAuthorizationRequest",
    "ToolAuthorizationResult",
    "ToolAuthorizer",
    "ToolCall",
    "ToolCapability",
    "ToolEffect",
    "ToolExecutionBudget",
    "ToolIntent",
    "ToolPrincipal",
    "ToolResource",
    "ToolResult",
    "TrustLevel",
    "ValidatedSystemPrompt",
    "ValidatedToolCall",
    "VectorAccessPolicy",
    "VectorChunk",
    "VectorEmbedding",
    "VectorIndexEntry",
    "VectorPrincipal",
    "VectorRetrievalHit",
    "VectorRetrievalPolicy",
    "VectorRetrievalRequest",
    "VectorVerificationCode",
    "VectorVerificationError",
    "VectorVerificationFinding",
    "VectorVerificationResult",
    # Version
    "__version__",
]
